[tool.poetry]
name = "viam-sdk"
version = "0.3.1rc1"
description = "Viam Robotics Python SDK"
authors = [ "Naveed <naveed@viam.com>" ]
license = "Apache-2.0"
readme = "README.md"
packages = [
  { include = "viam", from = "src" },
]
include = ["LICENSE", "src/viam/rpc/libviam_rust_utils.*"]

  [tool.poetry.dependencies]
  python = ">=3.8.1,<3.12"
  grpclib = "^0.4.4"
  googleapis-common-protos = "^1.59.0"
  typing-extensions = "^4.6.1"
  Pillow = "^9.5.0"
  protobuf = "^4.23.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"
coverage = "^7.2.6"
protoletariat = "^3.2.8"
jupyter = "^1.0.0"
flake8 = "^6.0.0"
myst-nb = "^0.17.2"
sphinx-autoapi = "^2.1.0"
sphinx-rtd-theme = "^1.2.1"
autopep8 = "^2.0.2"
black = "^23.3.0"
nbmake = "^1.4.1"
types-pillow = "^9.5.0.4"
mypy-protobuf = "^3.4.0"
tox = "^4.5.1"
isort = "^5.12.0"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = "tests"
asyncio_mode = "auto"

[tool.coverage.run]
omit = [ "*/gen/*" ]

[tool.coverage.report]
exclude_lines = [ "pragma: no\\s*cover", "\\.\\.\\." ]

[tool.black]
line-length = 140

[tool.isort]
profile = "black"
skip_glob = ["**/gen/**"]
line_length = 140

[build-system]
requires = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"
