[tool.poetry]
name = "viam-sdk"
version = "0.2.2"
description = "Viam Robotics Python SDK"
authors = [ "Naveed <naveed@viam.com>" ]
license = "Apache-2.0"
readme = "README.md"
packages = [
  { include = "viam", from = "src" },
]
include = ["LICENSE", "src/viam/rpc/libviam_rust_utils.*"]

  [tool.poetry.dependencies]
  python = ">=3.8,<=3.11"
  grpclib = "^0.4.3"
  googleapis-common-protos = "^1.57.0"
  typing-extensions = "^4.4.0"
  Pillow = "^9.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-asyncio = "^0.20.2"
coverage = "^6.5.0"
protoletariat = "^1.1.0"
jupyter = "^1.0.0"
flake8 = "^5.0.4"
myst-nb = "^0.17.1"
sphinx-autoapi = "^2.0.0"
sphinx-rtd-theme = "^1.1.1"
autopep8 = "^2.0.0"
black = "^22.10.0"
nbmake = "1.3.0"
types-pillow = "^9.3.0.1"
mypy-protobuf = "3.3.0"
protobuf = "3.20.3"
tox = "^3.27.1"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = "tests"
asyncio_mode = "auto"

[tool.coverage.run]
omit = [ "*/gen/*" ]

[tool.coverage.report]
exclude_lines = [ "pragma: no\\s*cover", "\\.\\.\\." ]

[tool.black]
line-length = 140

[tool.isort]
profile = "black"

[build-system]
requires = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"
