name: Build Wheels

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: macosx_x86_64
            ext: dylib
            whl: macosx_10_16_x86_64
          - arch: macosx_arm64
            ext: dylib
            whl: macosx_11_0_arm64
          - arch: linux_aarch64
            ext: so
            whl: manylinux2014_aarch64
          - arch: linux_x86_64
            ext: so
            whl: manylinux2014_x86_64
          - arch: musllinux_x86_64
            ext: so
            whl: musllinux_1_2_x86_64
          - arch: musllinux_x86
            ext: so
            whl: musllinux_1_2_i686
          - arch: musllinux_aarch64
            ext: so
            whl: musllinux_1_2_aarch64
          - arch: musllinux_armv7l
            ext: so
            whl: musllinux_1_2_armv7l
          - arch: linux_armv6l
            ext: so
            whl: linux_armv6l
          - arch: linux_armv6l
            ext: so
            whl: linux_armv7l
          - arch: windows_x86_64
            ext: dll
            whl: win_amd64
    steps:
      - name: Checkout Code - Call
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
        if: ${{ inputs.branch }}
      - name: Checkout Code - Dispatch
        uses: actions/checkout@v4
        if: ${{ !inputs.branch }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Setup Python
        run: uv python install 3.12

      - name: Install package
        run: uv sync

      - name: Download binary
        run: curl -sL -o src/viam/rpc/libviam_rust_utils.${{ matrix.ext }} https://github.com/viamrobotics/rust-utils/releases/latest/download/libviam_rust_utils-${{ matrix.arch }}.${{ matrix.ext }}

      - name: HACK for arm7l
        if: ${{ matrix.whl == 'linux_armv7l' }}
        run: echo "This file enables arm7l support. PyPI doesn't allow for packages with the same hash, so this file must be added to differentiate this arm7l package from the arm6l package." > src/viam/arm7l.txt

      - name: Build
        run: uv build --wheel

      - name: Rename
        run: |
          echo "WHL_NAME=viam_sdk-$(uv run python3 -c 'import viam; print(viam.__version__)')-py3-none-${{ matrix.whl }}.whl" >> $GITHUB_ENV
          mv dist/viam_sdk-$(uv run python3 -c "import viam; print(viam.__version__)")-py3-none-any.whl dist/viam_sdk-$(uv run python3 -c 'import viam; print(viam.__version__)')-py3-none-${{ matrix.whl }}.whl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WHL_NAME }}
          path: dist/${{ env.WHL_NAME }}
