name: License Finder

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

jobs:
  license_finder:
    if: github.repository_owner == 'viamrobotics'
    name: Audit 3rd-Party Licenses
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Setup Python
        run: uv python install

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - run: gem install license_finder

      - name: Generate requirements.txt (exclude dev dependencies)
        run: |
          uv pip compile pyproject.toml -o requirements.txt
          pip install -r requirements.txt

      - name: Run license finder
        run: |
          license_finder
