name: License Finder

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

jobs:
  license_finder:
    if: github.repository_owner == 'viamrobotics'
    name: Audit 3rd-Party Licenses
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - run: gem install license_finder

      - name: Install package
        run: poetry install --all-extras

      - name: Generate requirements.txt (exclude dev dependencies)
        run: |
          poetry export -f requirements.txt --without-hashes > requirements.txt
          pip install -r requirements.txt

      - name: Run license finder
        run: |
          python3 /opt/hostedtoolcache/Ruby/*/x64/lib/ruby/gems/*/gems/license_finder-*/bin/license_finder_pip.py requirements.txt
