name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_target:
    branches: [main, 'rc-*']

jobs:
  test:
    if: github.repository_owner == 'viamrobotics'
    runs-on: buildjet-2vcpu-ubuntu-2204
    container:
      image: python:${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        requirements-version: ["min", "max"]
    steps:
      - name: Checkout Push/Workflow Dispatch
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        uses: actions/checkout@v3
      - name: Checkout PR
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Fix Poetry
        run: poetry config installer.modern-installation false

      - name: Install package
        run: make install

      - name: Install minimum package versions
        run: poetry run pip install -r requirements-test.txt
        if: ${{ matrix.requirements-version == 'min' }}

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Test Documentation
        run: make test_docs
